### PR TITLE
[IMP] Extract list with games that should have run.bat handled

### PR DESCRIPTION
**Pull request by memmaker**
Might I suggest something like this, then?
This makes it impossible for the two lists to diverge, which they already did.

### CODE REVIEW

**Comment by Voljega** [comment]
Very good idea but I feel that the list would be better as a static var in `gamegenerator.py` rather than creating a new `lists.py` file

**Comment by memmaker** [comment]
Hmm, currently we have a dependency from gamegenerator to confconverter.
Doing what you suggest would create a new one from confconverter to gamegenerator.
Not sure if that would be a good idea.
I also think having the data part as far away from the code increases readability.
I either want to change the list with data or I want to change the code that handles it.
Files are cheap, big files are hard to navigate, the smaller the better.

Your call.

**Comment by Voljega** [comment]
Ok good and fair point about the dependencies cycling
One note on the naming conventions : better to not have any `_`.
I used camel case, although it's recommanded to use only lowercase for python, you can use one of the two like you prefer

**Comment by memmaker** [comment]
I adapted the change to your naming conventions.

**Comment by Voljega** [comment]
Thank you for the PR :)

**Comment by memmaker** [comment]
You are welcome. Thanks for your efforts on the project.

**Pull request merged**
